
import matplotlib.figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
import pandas as pd
import os
import uuid
import asyncio
from typing import Any, List, Optional, Dict

async def generate_graph(
    data_file_path: str,
    graph_type: str,
    x_column: str,
    y_columns: List[str],
    title: str = "Graph"
) -> Dict[str, Any]:
    """
    Generates a graph from a CSV data file and saves it as an image.
    
    Args:
        data_file_path (str): Path to the CSV file (usually generated by analyze_document).
        graph_type (str): Type of graph ('line', 'bar', 'scatter', 'pie').
        x_column (str): Column name for X-axis.
        y_columns (List[str]): List of column names for Y-axis.
        title (str): Title of the graph.
    """
    if not os.path.exists(data_file_path):
        return {"error": f"Data file not found: {data_file_path}"}
    
    try:
        loop = asyncio.get_running_loop()
        
        def _generate():
            df = pd.read_csv(data_file_path)
            
            # Check columns
            if x_column not in df.columns:
                return {"error": f"Column '{x_column}' not found in data. Available: {list(df.columns)}"}
            for col in y_columns:
                if col not in df.columns:
                    return {"error": f"Column '{col}' not found in data. Available: {list(df.columns)}"}
            
            # Setup Figure (Object-Oriented Interface - Thread Safe)
            fig = matplotlib.figure.Figure(figsize=(10, 6))
            canvas = FigureCanvas(fig)
            ax = fig.add_subplot(111)
            
            # Korean Font Support (Fallbacks)
            # Try to find a font that supports Korean
            # For Linux (Docker), usually explicit font installation is needed.
            # Check commonly available fonts
            # font_check = [f for f in plt.rcParams['font.sans-serif'] if 'Nanum' in f or 'Gothic' in f]
            # if not font_check:
            #      pass
            
            ax.set_title(title)
            
            # Plotting
            if graph_type == 'line':
                for y_col in y_columns:
                    ax.plot(df[x_column], df[y_col], label=y_col, marker='o')
            
            elif graph_type == 'bar':
                # Simple bar plot
                if len(y_columns) == 1:
                    ax.bar(df[x_column], df[y_columns[0]], label=y_columns[0])
                else:
                    df.plot(x=x_column, y=y_columns, kind='bar', ax=ax)
                    
            elif graph_type == 'scatter':
                for y_col in y_columns:
                    ax.scatter(df[x_column], df[y_col], label=y_col)
                    
            elif graph_type == 'pie':
                if len(y_columns) > 1:
                    return {"error": "Pie chart only supports one Y column."}
                ax.pie(df[y_columns[0]], labels=df[x_column], autopct='%1.1f%%')
                
            else:
                return {"error": f"Unsupported graph type: {graph_type}"}
                
            if graph_type != 'pie':
                ax.set_xlabel(x_column)
                ax.set_ylabel(", ".join(y_columns))
                ax.legend()
                ax.grid(True)
                
            # Save to file
            output_dir = "/app/outputs" # Standard path in many containers
            if not os.path.exists(output_dir):
                # Fallback to tmp if output dir doesn't exist
                output_dir = "/tmp"
            elif not os.access(output_dir, os.W_OK):
                 # Fallback if not writable
                 output_dir = "/tmp"
                
            filename = f"graph_{uuid.uuid4().hex}.png"
            output_path = os.path.join(output_dir, filename)
            
            canvas.print_figure(output_path)
            
            return {
                "result": "Graph generated successfully.",
                "file_path": output_path,
                "filename": filename
            }

        # Run within executor
        result = await loop.run_in_executor(None, _generate)
        return result
        
    except Exception as e:
        import traceback
        traceback.print_exc()
        return {"error": f"Failed to generate graph: {str(e)}"}
